### ISSUE TITLE
Updated "kafkacat" references with "kcat"

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-guides#283]
kafkacat was renamed to kcat in August 2021 due to trademark issues.

> The kafkacat project was renamed to kcat in August 2021 to adhere to the Apache Software Foundation's (ASF) trademark policies. Apart from the name, nothing else was changed.

https://github.com/edenhill/kcat#what-happened-to-kafkacat

**Comment by craicoverflow** [comment]
It looks as though the name is still "kafkacat" when downloaded through official sources such as `dnf` or `brew`. GitHub examples reference `kcat` though. Maybe we do not update this yet, but will need to some time in the future (probably soon).

**Comment by bhardesty** [comment]
FYI @sterobin

**Comment by sterobin** [comment]
@craicoverflow I suppose it makes more sense to wait until the change is complete on kcat's end, then make the change on ours.

**Comment by craicoverflow** [comment]
Yeah it does. It looks like they are partially there with the change, so it might be soon.

**Comment by sterobin** [comment]
@craicoverflow We've left this for now per @DuncanDoyle 's suggestion to pause, due to some bug or limitation. See this [jira conversation](https://issues.redhat.com/browse/MGDSTRM-5345?focusedCommentId=19062768&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-19062768).

But meanwhile, @jbyrne-redhat didn't you confirm that the kcat commands themselves did in fact also change form "kafkacat" to "kcat"?
